// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlogUser = `-- name: CreateBlogUser :one
INSERT INTO blog_users (blog_platform, user_id) VALUES ($1, $2)
ON CONFLICT (blog_platform, user_id) DO NOTHING
RETURNING blog_platform, user_id, last_enqueued_at, created_at
`

type CreateBlogUserParams struct {
	BlogPlatform string `json:"blog_platform"`
	UserID       string `json:"user_id"`
}

func (q *Queries) CreateBlogUser(ctx context.Context, arg CreateBlogUserParams) (BlogUser, error) {
	row := q.db.QueryRow(ctx, createBlogUser, arg.BlogPlatform, arg.UserID)
	var i BlogUser
	err := row.Scan(
		&i.BlogPlatform,
		&i.UserID,
		&i.LastEnqueuedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlogUser = `-- name: DeleteBlogUser :exec
DELETE FROM blog_users WHERE blog_platform = $1 AND user_id = $2
`

type DeleteBlogUserParams struct {
	BlogPlatform string `json:"blog_platform"`
	UserID       string `json:"user_id"`
}

func (q *Queries) DeleteBlogUser(ctx context.Context, arg DeleteBlogUserParams) error {
	_, err := q.db.Exec(ctx, deleteBlogUser, arg.BlogPlatform, arg.UserID)
	return err
}

const getBlogPost = `-- name: GetBlogPost :one

SELECT blog_platform, post_url, path, published_at, created_at, updated_at FROM blog_posts WHERE post_url = $1
`

// =============
// blog_posts
// =============
func (q *Queries) GetBlogPost(ctx context.Context, postUrl string) (BlogPost, error) {
	row := q.db.QueryRow(ctx, getBlogPost, postUrl)
	var i BlogPost
	err := row.Scan(
		&i.BlogPlatform,
		&i.PostUrl,
		&i.Path,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBlogUser = `-- name: GetBlogUser :one

SELECT blog_platform, user_id, last_enqueued_at, created_at FROM blog_users WHERE blog_platform = $1 AND user_id = $2
`

type GetBlogUserParams struct {
	BlogPlatform string `json:"blog_platform"`
	UserID       string `json:"user_id"`
}

// =============
// blog_users
// =============
func (q *Queries) GetBlogUser(ctx context.Context, arg GetBlogUserParams) (BlogUser, error) {
	row := q.db.QueryRow(ctx, getBlogUser, arg.BlogPlatform, arg.UserID)
	var i BlogUser
	err := row.Scan(
		&i.BlogPlatform,
		&i.UserID,
		&i.LastEnqueuedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listBlogPosts = `-- name: ListBlogPosts :many
SELECT blog_platform, post_url, path, published_at, created_at, updated_at FROM blog_posts
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListBlogPosts(ctx context.Context, limit int32) ([]BlogPost, error) {
	rows, err := q.db.Query(ctx, listBlogPosts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlogPost
	for rows.Next() {
		var i BlogPost
		if err := rows.Scan(
			&i.BlogPlatform,
			&i.PostUrl,
			&i.Path,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlogPostsByPlatform = `-- name: ListBlogPostsByPlatform :many
SELECT blog_platform, post_url, path, published_at, created_at, updated_at FROM blog_posts
WHERE blog_platform = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListBlogPostsByPlatformParams struct {
	BlogPlatform string `json:"blog_platform"`
	Limit        int32  `json:"limit"`
}

func (q *Queries) ListBlogPostsByPlatform(ctx context.Context, arg ListBlogPostsByPlatformParams) ([]BlogPost, error) {
	rows, err := q.db.Query(ctx, listBlogPostsByPlatform, arg.BlogPlatform, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlogPost
	for rows.Next() {
		var i BlogPost
		if err := rows.Scan(
			&i.BlogPlatform,
			&i.PostUrl,
			&i.Path,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlogUsers = `-- name: ListBlogUsers :many
SELECT blog_platform, user_id, last_enqueued_at, created_at FROM blog_users
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListBlogUsers(ctx context.Context, limit int32) ([]BlogUser, error) {
	rows, err := q.db.Query(ctx, listBlogUsers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlogUser
	for rows.Next() {
		var i BlogUser
		if err := rows.Scan(
			&i.BlogPlatform,
			&i.UserID,
			&i.LastEnqueuedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlogUsersOlderThan = `-- name: ListBlogUsersOlderThan :many
SELECT blog_platform, user_id, last_enqueued_at, created_at FROM blog_users
WHERE last_enqueued_at < $1
ORDER BY last_enqueued_at ASC
LIMIT $2
`

type ListBlogUsersOlderThanParams struct {
	LastEnqueuedAt pgtype.Timestamp `json:"last_enqueued_at"`
	Limit          int32            `json:"limit"`
}

func (q *Queries) ListBlogUsersOlderThan(ctx context.Context, arg ListBlogUsersOlderThanParams) ([]BlogUser, error) {
	rows, err := q.db.Query(ctx, listBlogUsersOlderThan, arg.LastEnqueuedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlogUser
	for rows.Next() {
		var i BlogUser
		if err := rows.Scan(
			&i.BlogPlatform,
			&i.UserID,
			&i.LastEnqueuedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlogUserLastEnqueuedAt = `-- name: UpdateBlogUserLastEnqueuedAt :exec
UPDATE blog_users SET last_enqueued_at = current_timestamp
WHERE blog_platform = $1 AND user_id = $2
`

type UpdateBlogUserLastEnqueuedAtParams struct {
	BlogPlatform string `json:"blog_platform"`
	UserID       string `json:"user_id"`
}

func (q *Queries) UpdateBlogUserLastEnqueuedAt(ctx context.Context, arg UpdateBlogUserLastEnqueuedAtParams) error {
	_, err := q.db.Exec(ctx, updateBlogUserLastEnqueuedAt, arg.BlogPlatform, arg.UserID)
	return err
}
